version: '3.8'
services:

  frontend:
    build:
      context: worknest-ui/
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./worknest-ui
        target: /app
    tty: true
    depends_on:
      - backend

  backend:
      build:
        context: worknest-service/
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_worknest
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
      depends_on:
        - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_worknest
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: