package com.ams.worknest.model.resources;

import lombok.*;

/**
 * Resource class representing the public-facing information of a user.
 * This class is used to encapsulate user data that is safe to expose through the API.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class UserResource {

    private String name;

    private String email;

    private String username;

    // Getters, setters, and builder are automatically generated by Lombok
}