# versione node usata da fabio 21.7.1
FROM node:21.7.1 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN chmod +x node_modules/.bin/vite
# RUN npm run build
# RUN npm run dev

# Fase di esecuzione
FROM nginx:stable-alpine as production-stage
# Copia l'applicazione buildata nel server nginx
COPY --from=build-stage /app/dist /usr/share/nginx/html
# COPY --from=build-stage /app /app
EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
ENTRYPOINT ["npm", "run", "dev"]