spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    schema: worknest
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
