spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:db/migrations
    enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true


